[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace]
resolver = "2"
members = [
  "libs/gl-client",
  "libs/gl-client-py",
  "libs/gl-plugin",
  "libs/gl-signerproxy",
]

[workspace.dependencies]
anyhow = "1"
env_logger = "0.10"
cln-grpc = "0.1.7"
cln-rpc = "0.1.7"
cln-plugin = "0.1.7"

vls-core = "=0.11.0-rc.2"
vls-persist = "=0.11.0-rc.2"
vls-protocol-signer = "=0.11.0-rc.2"
vls-protocol = "=0.11.0-rc.2"


# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.4.2"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin"]
# Publish jobs to run in CI
pr-run-mode = "upload"

allow-dirty = ["ci"]
