"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HsmRequestContext(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: _builtins.int
    DBID_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    node_id: _builtins.bytes
    dbid: _builtins.int
    capabilities: _builtins.int
    def __init__(
        self,
        *,
        node_id: _builtins.bytes = ...,
        dbid: _builtins.int = ...,
        capabilities: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "dbid", b"dbid", "node_id", b"node_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HsmRequestContext: _TypeAlias = HsmRequestContext  # noqa: Y015

@_typing.final
class HsmResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    RAW_FIELD_NUMBER: _builtins.int
    SIGNER_STATE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    request_id: _builtins.int
    raw: _builtins.bytes
    error: _builtins.str
    """If the signer reported an error, and did therefore not include
    `raw`, this is the stringified error, so we can print it in the
    logs. This should help us collate policy errors with the changes
    proposed by CLN
    """
    @_builtins.property
    def signer_state(self) -> _containers.RepeatedCompositeFieldContainer[Global___SignerStateEntry]:
        """A list of updated key-value-version tuples that is to be
        merged into the state tracked by the plugin.
        """

    def __init__(
        self,
        *,
        request_id: _builtins.int = ...,
        raw: _builtins.bytes = ...,
        signer_state: _abc.Iterable[Global___SignerStateEntry] | None = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "raw", b"raw", "request_id", b"request_id", "signer_state", b"signer_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HsmResponse: _TypeAlias = HsmResponse  # noqa: Y015

@_typing.final
class HsmRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    RAW_FIELD_NUMBER: _builtins.int
    SIGNER_STATE_FIELD_NUMBER: _builtins.int
    REQUESTS_FIELD_NUMBER: _builtins.int
    request_id: _builtins.int
    raw: _builtins.bytes
    @_builtins.property
    def context(self) -> Global___HsmRequestContext: ...
    @_builtins.property
    def signer_state(self) -> _containers.RepeatedCompositeFieldContainer[Global___SignerStateEntry]:
        """A list of key-value-version tuples that the signer should
        use to update its internal state.
        """

    @_builtins.property
    def requests(self) -> _containers.RepeatedCompositeFieldContainer[Global___PendingRequest]:
        """Currently active requests that are used to justify changes
        in state.
        """

    def __init__(
        self,
        *,
        request_id: _builtins.int = ...,
        context: Global___HsmRequestContext | None = ...,
        raw: _builtins.bytes = ...,
        signer_state: _abc.Iterable[Global___SignerStateEntry] | None = ...,
        requests: _abc.Iterable[Global___PendingRequest] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "raw", b"raw", "request_id", b"request_id", "requests", b"requests", "signer_state", b"signer_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HsmRequest: _TypeAlias = HsmRequest  # noqa: Y015

@_typing.final
class Empty(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Empty: _TypeAlias = Empty  # noqa: Y015

@_typing.final
class Amount(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MILLISATOSHI_FIELD_NUMBER: _builtins.int
    SATOSHI_FIELD_NUMBER: _builtins.int
    BITCOIN_FIELD_NUMBER: _builtins.int
    ALL_FIELD_NUMBER: _builtins.int
    ANY_FIELD_NUMBER: _builtins.int
    millisatoshi: _builtins.int
    satoshi: _builtins.int
    bitcoin: _builtins.int
    all: _builtins.bool
    any: _builtins.bool
    def __init__(
        self,
        *,
        millisatoshi: _builtins.int = ...,
        satoshi: _builtins.int = ...,
        bitcoin: _builtins.int = ...,
        all: _builtins.bool = ...,
        any: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["all", b"all", "any", b"any", "bitcoin", b"bitcoin", "millisatoshi", b"millisatoshi", "satoshi", b"satoshi", "unit", b"unit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["all", b"all", "any", b"any", "bitcoin", b"bitcoin", "millisatoshi", b"millisatoshi", "satoshi", b"satoshi", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_unit: _TypeAlias = _typing.Literal["millisatoshi", "satoshi", "bitcoin", "all", "any"]  # noqa: Y015
    _WhichOneofArgType_unit: _TypeAlias = _typing.Literal["unit", b"unit"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_unit) -> _WhichOneofReturnType_unit | None: ...

Global___Amount: _TypeAlias = Amount  # noqa: Y015

@_typing.final
class TlvField(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    type: _builtins.int
    value: _builtins.bytes
    """length is implied since the value field carries its own
    length here.
    """
    def __init__(
        self,
        *,
        type: _builtins.int = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TlvField: _TypeAlias = TlvField  # noqa: Y015

@_typing.final
class OffChainPayment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    PREIMAGE_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    EXTRATLVS_FIELD_NUMBER: _builtins.int
    PAYMENT_HASH_FIELD_NUMBER: _builtins.int
    BOLT11_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    preimage: _builtins.bytes
    payment_hash: _builtins.bytes
    bolt11: _builtins.str
    @_builtins.property
    def amount(self) -> Global___Amount: ...
    @_builtins.property
    def extratlvs(self) -> _containers.RepeatedCompositeFieldContainer[Global___TlvField]: ...
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        preimage: _builtins.bytes = ...,
        amount: Global___Amount | None = ...,
        extratlvs: _abc.Iterable[Global___TlvField] | None = ...,
        payment_hash: _builtins.bytes = ...,
        bolt11: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "bolt11", b"bolt11", "extratlvs", b"extratlvs", "label", b"label", "payment_hash", b"payment_hash", "preimage", b"preimage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OffChainPayment: _TypeAlias = OffChainPayment  # noqa: Y015

@_typing.final
class IncomingPayment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OFFCHAIN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def offchain(self) -> Global___OffChainPayment: ...
    def __init__(
        self,
        *,
        offchain: Global___OffChainPayment | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["details", b"details", "offchain", b"offchain"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["details", b"details", "offchain", b"offchain"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_details: _TypeAlias = _typing.Literal["offchain"]  # noqa: Y015
    _WhichOneofArgType_details: _TypeAlias = _typing.Literal["details", b"details"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_details) -> _WhichOneofReturnType_details | None: ...

Global___IncomingPayment: _TypeAlias = IncomingPayment  # noqa: Y015

@_typing.final
class StreamLogRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StreamLogRequest: _TypeAlias = StreamLogRequest  # noqa: Y015

@_typing.final
class LogEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LINE_FIELD_NUMBER: _builtins.int
    line: _builtins.str
    def __init__(
        self,
        *,
        line: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["line", b"line"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogEntry: _TypeAlias = LogEntry  # noqa: Y015

@_typing.final
class SignerStateEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    def __init__(
        self,
        *,
        version: _builtins.int = ...,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SignerStateEntry: _TypeAlias = SignerStateEntry  # noqa: Y015

@_typing.final
class PendingRequest(_message.Message):
    """This represents a grpc request that is currently pending, along
    with the pubkey of the client issuing the request and a matching
    signature. This allows the signer to verify that the state changes
    implied in a signature request correspond to authentic grpc
    commands, and were not injected somewhere along the way.
    """

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    SIGNATURE_FIELD_NUMBER: _builtins.int
    PUBKEY_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    RUNE_FIELD_NUMBER: _builtins.int
    request: _builtins.bytes
    uri: _builtins.str
    signature: _builtins.bytes
    pubkey: _builtins.bytes
    timestamp: _builtins.int
    rune: _builtins.bytes
    def __init__(
        self,
        *,
        request: _builtins.bytes = ...,
        uri: _builtins.str = ...,
        signature: _builtins.bytes = ...,
        pubkey: _builtins.bytes = ...,
        timestamp: _builtins.int = ...,
        rune: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pubkey", b"pubkey", "request", b"request", "rune", b"rune", "signature", b"signature", "timestamp", b"timestamp", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PendingRequest: _TypeAlias = PendingRequest  # noqa: Y015

@_typing.final
class NodeConfig(_message.Message):
    """The `NodeConfig` is used to pass startup parameters to the
    node. The `gl-plugin` will look for a file in its directory to load
    these values from. Please refer to the individual fields to learn
    what they do.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STARTUPMSGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def startupmsgs(self) -> _containers.RepeatedCompositeFieldContainer[Global___StartupMessage]:
        """In order to start without a signer attached we need to
        stash a couple of canned messages that we'd otherwise ask
        from the signer. These are just request-response tuples
        that we use to match and reply against incoming requests.
        """

    def __init__(
        self,
        *,
        startupmsgs: _abc.Iterable[Global___StartupMessage] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["startupmsgs", b"startupmsgs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NodeConfig: _TypeAlias = NodeConfig  # noqa: Y015

@_typing.final
class GlConfig(_message.Message):
    """The `GlConfig` is used to pass greenlight-specific startup parameters
    to the node. The `gl-plugin` will look for a serialized config object in 
    the node's datastore to load these values from. Please refer to the 
    individual fields to learn what they do.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CLOSE_TO_ADDR_FIELD_NUMBER: _builtins.int
    close_to_addr: _builtins.str
    def __init__(
        self,
        *,
        close_to_addr: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close_to_addr", b"close_to_addr"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GlConfig: _TypeAlias = GlConfig  # noqa: Y015

@_typing.final
class StartupMessage(_message.Message):
    """A message that we know will be requested by `lightningd` at
    startup, and that we stash a response to on the scheduler. This
    allows the scheduler to start a node without requiring the signer
    to connect first. Messages are stored in full, including type
    prefix, but without the length prefix.
    """

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_FIELD_NUMBER: _builtins.int
    RESPONSE_FIELD_NUMBER: _builtins.int
    request: _builtins.bytes
    response: _builtins.bytes
    def __init__(
        self,
        *,
        request: _builtins.bytes = ...,
        response: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request", b"request", "response", b"response"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartupMessage: _TypeAlias = StartupMessage  # noqa: Y015

@_typing.final
class StreamCustommsgRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StreamCustommsgRequest: _TypeAlias = StreamCustommsgRequest  # noqa: Y015

@_typing.final
class Custommsg(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PEER_ID_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    peer_id: _builtins.bytes
    payload: _builtins.bytes
    def __init__(
        self,
        *,
        peer_id: _builtins.bytes = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "peer_id", b"peer_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Custommsg: _TypeAlias = Custommsg  # noqa: Y015

@_typing.final
class TrampolinePayRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BOLT11_FIELD_NUMBER: _builtins.int
    TRAMPOLINE_NODE_ID_FIELD_NUMBER: _builtins.int
    AMOUNT_MSAT_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    MAXFEEPERCENT_FIELD_NUMBER: _builtins.int
    MAXDELAY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    bolt11: _builtins.str
    trampoline_node_id: _builtins.bytes
    amount_msat: _builtins.int
    label: _builtins.str
    maxfeepercent: _builtins.float
    maxdelay: _builtins.int
    description: _builtins.str
    def __init__(
        self,
        *,
        bolt11: _builtins.str = ...,
        trampoline_node_id: _builtins.bytes = ...,
        amount_msat: _builtins.int = ...,
        label: _builtins.str = ...,
        maxfeepercent: _builtins.float = ...,
        maxdelay: _builtins.int = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount_msat", b"amount_msat", "bolt11", b"bolt11", "description", b"description", "label", b"label", "maxdelay", b"maxdelay", "maxfeepercent", b"maxfeepercent", "trampoline_node_id", b"trampoline_node_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrampolinePayRequest: _TypeAlias = TrampolinePayRequest  # noqa: Y015

@_typing.final
class TrampolinePayResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _PayStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _PayStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TrampolinePayResponse._PayStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        COMPLETE: TrampolinePayResponse._PayStatus.ValueType  # 0
        FAILED: TrampolinePayResponse._PayStatus.ValueType  # 2

    class PayStatus(_PayStatus, metaclass=_PayStatusEnumTypeWrapper): ...
    COMPLETE: TrampolinePayResponse.PayStatus.ValueType  # 0
    FAILED: TrampolinePayResponse.PayStatus.ValueType  # 2

    PAYMENT_PREIMAGE_FIELD_NUMBER: _builtins.int
    PAYMENT_HASH_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    PARTS_FIELD_NUMBER: _builtins.int
    AMOUNT_MSAT_FIELD_NUMBER: _builtins.int
    AMOUNT_SENT_MSAT_FIELD_NUMBER: _builtins.int
    DESTINATION_FIELD_NUMBER: _builtins.int
    payment_preimage: _builtins.bytes
    payment_hash: _builtins.bytes
    created_at: _builtins.float
    parts: _builtins.int
    amount_msat: _builtins.int
    amount_sent_msat: _builtins.int
    destination: _builtins.bytes
    def __init__(
        self,
        *,
        payment_preimage: _builtins.bytes = ...,
        payment_hash: _builtins.bytes = ...,
        created_at: _builtins.float = ...,
        parts: _builtins.int = ...,
        amount_msat: _builtins.int = ...,
        amount_sent_msat: _builtins.int = ...,
        destination: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount_msat", b"amount_msat", "amount_sent_msat", b"amount_sent_msat", "created_at", b"created_at", "destination", b"destination", "parts", b"parts", "payment_hash", b"payment_hash", "payment_preimage", b"payment_preimage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrampolinePayResponse: _TypeAlias = TrampolinePayResponse  # noqa: Y015

@_typing.final
class LspInvoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LSP_ID_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    AMOUNT_MSAT_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    lsp_id: _builtins.str
    """len=0 => None, let the server decide."""
    token: _builtins.str
    """Optional: for discounts/API keys
    len=0 => None
    """
    amount_msat: _builtins.int
    """Pass-through of cln invoice rpc params
    0 => Any
    """
    description: _builtins.str
    label: _builtins.str
    def __init__(
        self,
        *,
        lsp_id: _builtins.str = ...,
        token: _builtins.str = ...,
        amount_msat: _builtins.int = ...,
        description: _builtins.str = ...,
        label: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount_msat", b"amount_msat", "description", b"description", "label", b"label", "lsp_id", b"lsp_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LspInvoiceRequest: _TypeAlias = LspInvoiceRequest  # noqa: Y015

@_typing.final
class LspInvoiceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BOLT11_FIELD_NUMBER: _builtins.int
    CREATED_INDEX_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    PAYMENT_HASH_FIELD_NUMBER: _builtins.int
    PAYMENT_SECRET_FIELD_NUMBER: _builtins.int
    bolt11: _builtins.str
    created_index: _builtins.int
    expires_at: _builtins.int
    payment_hash: _builtins.bytes
    payment_secret: _builtins.bytes
    def __init__(
        self,
        *,
        bolt11: _builtins.str = ...,
        created_index: _builtins.int = ...,
        expires_at: _builtins.int = ...,
        payment_hash: _builtins.bytes = ...,
        payment_secret: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bolt11", b"bolt11", "created_index", b"created_index", "expires_at", b"expires_at", "payment_hash", b"payment_hash", "payment_secret", b"payment_secret"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LspInvoiceResponse: _TypeAlias = LspInvoiceResponse  # noqa: Y015

@_typing.final
class NodeEventsRequest(_message.Message):
    """Request for streaming node events. Currently empty but defined as
    its own message type to allow adding filters in the future (e.g.,
    filter by event type, invoice label, etc.)
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___NodeEventsRequest: _TypeAlias = NodeEventsRequest  # noqa: Y015

@_typing.final
class NodeEvent(_message.Message):
    """A real-time event from the node. Uses oneof to discriminate between
    different event types.
    """

    DESCRIPTOR: _descriptor.Descriptor

    INVOICE_PAID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def invoice_paid(self) -> Global___InvoicePaid:
        """Future event types:
        PeerConnected peer_connected = 2;
        PeerDisconnected peer_disconnected = 3;
        ChannelStateChanged channel_state_changed = 4;
        BalanceChanged balance_changed = 5;
        """

    def __init__(
        self,
        *,
        invoice_paid: Global___InvoicePaid | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "invoice_paid", b"invoice_paid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "invoice_paid", b"invoice_paid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["invoice_paid"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___NodeEvent: _TypeAlias = NodeEvent  # noqa: Y015

@_typing.final
class InvoicePaid(_message.Message):
    """Event emitted when an invoice is paid."""

    DESCRIPTOR: _descriptor.Descriptor

    PAYMENT_HASH_FIELD_NUMBER: _builtins.int
    BOLT11_FIELD_NUMBER: _builtins.int
    PREIMAGE_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    AMOUNT_MSAT_FIELD_NUMBER: _builtins.int
    EXTRATLVS_FIELD_NUMBER: _builtins.int
    payment_hash: _builtins.bytes
    """The payment hash of the paid invoice."""
    bolt11: _builtins.str
    """The bolt11 invoice string."""
    preimage: _builtins.bytes
    """The preimage that proves payment."""
    label: _builtins.str
    """The label assigned to the invoice."""
    amount_msat: _builtins.int
    """Amount received in millisatoshis."""
    @_builtins.property
    def extratlvs(self) -> _containers.RepeatedCompositeFieldContainer[Global___TlvField]:
        """Extra TLV fields included in the payment."""

    def __init__(
        self,
        *,
        payment_hash: _builtins.bytes = ...,
        bolt11: _builtins.str = ...,
        preimage: _builtins.bytes = ...,
        label: _builtins.str = ...,
        amount_msat: _builtins.int = ...,
        extratlvs: _abc.Iterable[Global___TlvField] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount_msat", b"amount_msat", "bolt11", b"bolt11", "extratlvs", b"extratlvs", "label", b"label", "payment_hash", b"payment_hash", "preimage", b"preimage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InvoicePaid: _TypeAlias = InvoicePaid  # noqa: Y015
