[package]
name = "gl-signerproxy"
version = "0.3.1"
edition = "2021"
authors = [
        "Christian Decker",
        "The Greenlight Team"
]
description = "Python bindings for the Greenlight client library."
repository = "https://github.com/Blockstream/greenlight"
license = "MIT"

[[bin]]
name = "gl-signerproxy"
path = "src/bin/signerproxy.rs"

[build-dependencies]
tonic-prost-build = "0.14"

[dependencies]
anyhow = { workspace = true }
env_logger = { workspace = true }
tokio = { version = "1", features = ["rt", "net", "io-util"] }
tonic = { version = "0.14", features = ["tls-ring", "transport"] }
prost = "0.14"
tonic-prost = "0.14"
log = "*"
tower = { version = "0.5", features = ["util"] }
hyper-util = { version = "0.1", features = ["tokio"] }
which = "4.4.2"
libc = "0.2"
byteorder = "1.5.0"
