version: "3"

tasks:
  install-protoc:
    dir: '/tmp'
    env:
      PROTOC_VERSION: 3.19.3
    cmds:
      - wget https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip --quiet -O protoc.zip
      - unzip protoc.zip
      - mkdir -p {{ .HOME }}/bin/
      - mv bin/protoc {{ .HOME }}/bin/
      - rm protoc.zip

  install-cfssl:
    env:
      BASE: "https://github.com/cloudflare/cfssl/releases/download/"
      VERSION: 1.5.0
    dir: /tmp/
    cmds:
      - mkdir bin/
      - wget -q {{ .BASE }}/{{ .VERSION }}/cfssl_{{ .VERSION }}_linux_amd64 -O bin/cfssl
      - wget -q {{ .BASE }}/{{ .VERSION }}/cfssljson_{{ .VERSION }}_linux_amd64 -O bin/cfssljson
      - chmod a+x /tmp/bin/cfssljson
      - chmod a+x /tmp/bin/cfssl
