// This file was auto-generated by `gl-msggen`. Do not edit, as changes
// are lost when regenerating. See http://bit.ly/48GGgcJ for details on
// the generator.

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetinfoResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListpeersResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListfundsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendpayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListchannelsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AddgossipResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AddpsbtoutputResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AutocleanonceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AutocleanstatusResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CheckmessageResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CloseResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ConnectResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CreateinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DatastoreResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DatastoreusageResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CreateonionResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DeldatastoreResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DelinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DevforgetchannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct EmergencyrecoverResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetemergencyrecoverdataResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ExposesecretResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RecoverResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RecoverchannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InvoicerequestResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DisableinvoicerequestResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListinvoicerequestsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListdatastoreResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListinvoicesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendonionResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListsendpaysResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListtransactionsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct MakesecretResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListnodesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitanyinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitsendpayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct NewaddrResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WithdrawResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct KeysendResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundpsbtResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendpsbtResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SignpsbtResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct UtxopsbtResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct TxdiscardResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct TxprepareResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct TxsendResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListpeerchannelsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListclosedchannelsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DecodepayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DecodeResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DelpayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DelforwardResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DisableofferResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct EnableofferResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DisconnectResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FeeratesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FetchinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelCancelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelCompleteResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelStartResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetlogResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FunderupdateResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetrouteResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListaddressesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListforwardsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListoffersResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListpaysResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListhtlcsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct MultifundchannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct MultiwithdrawResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OfferResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelAbortResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelBumpResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelInitResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelSignedResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelUpdateResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PingResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PluginResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RenepaystatusResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RenepayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ReserveinputsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendcustommsgResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SetchannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SetconfigResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SetpsbtversionResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SigninvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SignmessageResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SpliceInitResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SpliceSignedResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SpliceUpdateResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DevspliceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct UnreserveinputsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct UpgradewalletResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitblockheightResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListconfigsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct StopResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct HelpResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PreapprovekeysendResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PreapproveinvoiceResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct StaticbackupResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprchannelsapyResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprdumpincomecsvResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprinspectResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprlistaccounteventsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprlistbalancesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprlistincomeResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkpreditdescriptionbypaymentidResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkpreditdescriptionbyoutpointResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BlacklistruneResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CheckruneResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CreateruneResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ShowrunesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneunreserveResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenelistlayersResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenecreatelayerResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneremovelayerResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenereserveResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneageResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetroutesResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenedisablenodeResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneinformchannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenecreatechannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneupdatechannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenebiaschannelResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenelistreservationsResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InjectpaymentonionResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InjectonionmessageResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct XpayResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SignmessagewithkeyResponse {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetinfoRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListpeersRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListfundsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendpayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListchannelsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AddgossipRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AddpsbtoutputRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AutocleanonceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AutocleanstatusRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CheckmessageRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CloseRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ConnectRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CreateinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DatastoreRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DatastoreusageRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CreateonionRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DeldatastoreRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DelinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DevforgetchannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct EmergencyrecoverRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetemergencyrecoverdataRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ExposesecretRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RecoverRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RecoverchannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InvoicerequestRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DisableinvoicerequestRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListinvoicerequestsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListdatastoreRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListinvoicesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendonionRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListsendpaysRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListtransactionsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct MakesecretRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListnodesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitanyinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitsendpayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct NewaddrRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WithdrawRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct KeysendRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundpsbtRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendpsbtRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SignpsbtRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct UtxopsbtRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct TxdiscardRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct TxprepareRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct TxsendRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListpeerchannelsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListclosedchannelsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DecodepayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DecodeRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DelpayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DelforwardRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DisableofferRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct EnableofferRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DisconnectRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FeeratesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FetchinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelCancelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelCompleteRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FundchannelStartRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetlogRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct FunderupdateRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetrouteRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListaddressesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListforwardsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListoffersRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListpaysRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListhtlcsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct MultifundchannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct MultiwithdrawRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OfferRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelAbortRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelBumpRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelInitRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelSignedRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct OpenchannelUpdateRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PingRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PluginRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RenepaystatusRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct RenepayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ReserveinputsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendcustommsgRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SendinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SetchannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SetconfigRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SetpsbtversionRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SigninvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SignmessageRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SpliceInitRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SpliceSignedRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SpliceUpdateRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct DevspliceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct UnreserveinputsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct UpgradewalletRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitblockheightRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct WaitRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ListconfigsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct StopRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct HelpRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PreapprovekeysendRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct PreapproveinvoiceRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct StaticbackupRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprchannelsapyRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprdumpincomecsvRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprinspectRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprlistaccounteventsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprlistbalancesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkprlistincomeRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkpreditdescriptionbypaymentidRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BkpreditdescriptionbyoutpointRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct BlacklistruneRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CheckruneRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct CreateruneRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct ShowrunesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneunreserveRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenelistlayersRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenecreatelayerRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneremovelayerRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenereserveRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneageRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct GetroutesRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenedisablenodeRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneinformchannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenecreatechannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskreneupdatechannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenebiaschannelRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct AskrenelistreservationsRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InjectpaymentonionRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct InjectonionmessageRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct XpayRequest {
}

#[allow(non_camel_case_types)]
#[derive(Clone, Debug)]
pub struct SignmessagewithkeyRequest {
}

pub struct Node {
}

impl Node {

  pub fn new() -> Node {
  Node {  }
}
#[allow(non_snake_case)]
pub fn Getinfo(&self, request: GetinfoRequest) -> GetinfoResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListPeers(&self, request: ListpeersRequest) -> ListpeersResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListFunds(&self, request: ListfundsRequest) -> ListfundsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SendPay(&self, request: SendpayRequest) -> SendpayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListChannels(&self, request: ListchannelsRequest) -> ListchannelsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AddGossip(&self, request: AddgossipRequest) -> AddgossipResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AddPsbtOutput(&self, request: AddpsbtoutputRequest) -> AddpsbtoutputResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AutoCleanOnce(&self, request: AutocleanonceRequest) -> AutocleanonceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AutoCleanStatus(&self, request: AutocleanstatusRequest) -> AutocleanstatusResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn CheckMessage(&self, request: CheckmessageRequest) -> CheckmessageResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Close(&self, request: CloseRequest) -> CloseResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Connect(&self, request: ConnectRequest) -> ConnectResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn CreateInvoice(&self, request: CreateinvoiceRequest) -> CreateinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Datastore(&self, request: DatastoreRequest) -> DatastoreResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DatastoreUsage(&self, request: DatastoreusageRequest) -> DatastoreusageResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn CreateOnion(&self, request: CreateonionRequest) -> CreateonionResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DelDatastore(&self, request: DeldatastoreRequest) -> DeldatastoreResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DelInvoice(&self, request: DelinvoiceRequest) -> DelinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DevForgetChannel(&self, request: DevforgetchannelRequest) -> DevforgetchannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn EmergencyRecover(&self, request: EmergencyrecoverRequest) -> EmergencyrecoverResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn GetEmergencyRecoverData(&self, request: GetemergencyrecoverdataRequest) -> GetemergencyrecoverdataResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ExposeSecret(&self, request: ExposesecretRequest) -> ExposesecretResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Recover(&self, request: RecoverRequest) -> RecoverResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn RecoverChannel(&self, request: RecoverchannelRequest) -> RecoverchannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Invoice(&self, request: InvoiceRequest) -> InvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn InvoiceRequest(&self, request: InvoicerequestRequest) -> InvoicerequestResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DisableInvoiceRequest(&self, request: DisableinvoicerequestRequest) -> DisableinvoicerequestResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListInvoiceRequests(&self, request: ListinvoicerequestsRequest) -> ListinvoicerequestsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListDatastore(&self, request: ListdatastoreRequest) -> ListdatastoreResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListInvoices(&self, request: ListinvoicesRequest) -> ListinvoicesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SendOnion(&self, request: SendonionRequest) -> SendonionResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListSendPays(&self, request: ListsendpaysRequest) -> ListsendpaysResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListTransactions(&self, request: ListtransactionsRequest) -> ListtransactionsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn MakeSecret(&self, request: MakesecretRequest) -> MakesecretResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Pay(&self, request: PayRequest) -> PayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListNodes(&self, request: ListnodesRequest) -> ListnodesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn WaitAnyInvoice(&self, request: WaitanyinvoiceRequest) -> WaitanyinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn WaitInvoice(&self, request: WaitinvoiceRequest) -> WaitinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn WaitSendPay(&self, request: WaitsendpayRequest) -> WaitsendpayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn NewAddr(&self, request: NewaddrRequest) -> NewaddrResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Withdraw(&self, request: WithdrawRequest) -> WithdrawResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn KeySend(&self, request: KeysendRequest) -> KeysendResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FundPsbt(&self, request: FundpsbtRequest) -> FundpsbtResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SendPsbt(&self, request: SendpsbtRequest) -> SendpsbtResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SignPsbt(&self, request: SignpsbtRequest) -> SignpsbtResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn UtxoPsbt(&self, request: UtxopsbtRequest) -> UtxopsbtResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn TxDiscard(&self, request: TxdiscardRequest) -> TxdiscardResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn TxPrepare(&self, request: TxprepareRequest) -> TxprepareResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn TxSend(&self, request: TxsendRequest) -> TxsendResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListPeerChannels(&self, request: ListpeerchannelsRequest) -> ListpeerchannelsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListClosedChannels(&self, request: ListclosedchannelsRequest) -> ListclosedchannelsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DecodePay(&self, request: DecodepayRequest) -> DecodepayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Decode(&self, request: DecodeRequest) -> DecodeResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DelPay(&self, request: DelpayRequest) -> DelpayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DelForward(&self, request: DelforwardRequest) -> DelforwardResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DisableOffer(&self, request: DisableofferRequest) -> DisableofferResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn EnableOffer(&self, request: EnableofferRequest) -> EnableofferResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Disconnect(&self, request: DisconnectRequest) -> DisconnectResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Feerates(&self, request: FeeratesRequest) -> FeeratesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FetchInvoice(&self, request: FetchinvoiceRequest) -> FetchinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FundChannelCancel(&self, request: FundchannelCancelRequest) -> FundchannelCancelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FundChannelComplete(&self, request: FundchannelCompleteRequest) -> FundchannelCompleteResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FundChannel(&self, request: FundchannelRequest) -> FundchannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FundChannelStart(&self, request: FundchannelStartRequest) -> FundchannelStartResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn GetLog(&self, request: GetlogRequest) -> GetlogResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn FunderUpdate(&self, request: FunderupdateRequest) -> FunderupdateResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn GetRoute(&self, request: GetrouteRequest) -> GetrouteResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListAddresses(&self, request: ListaddressesRequest) -> ListaddressesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListForwards(&self, request: ListforwardsRequest) -> ListforwardsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListOffers(&self, request: ListoffersRequest) -> ListoffersResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListPays(&self, request: ListpaysRequest) -> ListpaysResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListHtlcs(&self, request: ListhtlcsRequest) -> ListhtlcsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn MultiFundChannel(&self, request: MultifundchannelRequest) -> MultifundchannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn MultiWithdraw(&self, request: MultiwithdrawRequest) -> MultiwithdrawResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Offer(&self, request: OfferRequest) -> OfferResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn OpenChannelAbort(&self, request: OpenchannelAbortRequest) -> OpenchannelAbortResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn OpenChannelBump(&self, request: OpenchannelBumpRequest) -> OpenchannelBumpResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn OpenChannelInit(&self, request: OpenchannelInitRequest) -> OpenchannelInitResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn OpenChannelSigned(&self, request: OpenchannelSignedRequest) -> OpenchannelSignedResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn OpenChannelUpdate(&self, request: OpenchannelUpdateRequest) -> OpenchannelUpdateResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Ping(&self, request: PingRequest) -> PingResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Plugin(&self, request: PluginRequest) -> PluginResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn RenePayStatus(&self, request: RenepaystatusRequest) -> RenepaystatusResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn RenePay(&self, request: RenepayRequest) -> RenepayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ReserveInputs(&self, request: ReserveinputsRequest) -> ReserveinputsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SendCustomMsg(&self, request: SendcustommsgRequest) -> SendcustommsgResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SendInvoice(&self, request: SendinvoiceRequest) -> SendinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SetChannel(&self, request: SetchannelRequest) -> SetchannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SetConfig(&self, request: SetconfigRequest) -> SetconfigResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SetPsbtVersion(&self, request: SetpsbtversionRequest) -> SetpsbtversionResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SignInvoice(&self, request: SigninvoiceRequest) -> SigninvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SignMessage(&self, request: SignmessageRequest) -> SignmessageResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SpliceInit(&self, request: SpliceInitRequest) -> SpliceInitResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SpliceSigned(&self, request: SpliceSignedRequest) -> SpliceSignedResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SpliceUpdate(&self, request: SpliceUpdateRequest) -> SpliceUpdateResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn DevSplice(&self, request: DevspliceRequest) -> DevspliceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn UnreserveInputs(&self, request: UnreserveinputsRequest) -> UnreserveinputsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn UpgradeWallet(&self, request: UpgradewalletRequest) -> UpgradewalletResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn WaitBlockHeight(&self, request: WaitblockheightRequest) -> WaitblockheightResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Wait(&self, request: WaitRequest) -> WaitResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ListConfigs(&self, request: ListconfigsRequest) -> ListconfigsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Stop(&self, request: StopRequest) -> StopResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Help(&self, request: HelpRequest) -> HelpResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn PreApproveKeysend(&self, request: PreapprovekeysendRequest) -> PreapprovekeysendResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn PreApproveInvoice(&self, request: PreapproveinvoiceRequest) -> PreapproveinvoiceResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn StaticBackup(&self, request: StaticbackupRequest) -> StaticbackupResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprChannelsApy(&self, request: BkprchannelsapyRequest) -> BkprchannelsapyResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprDumpIncomeCsv(&self, request: BkprdumpincomecsvRequest) -> BkprdumpincomecsvResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprInspect(&self, request: BkprinspectRequest) -> BkprinspectResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprListAccountEvents(&self, request: BkprlistaccounteventsRequest) -> BkprlistaccounteventsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprListBalances(&self, request: BkprlistbalancesRequest) -> BkprlistbalancesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprListIncome(&self, request: BkprlistincomeRequest) -> BkprlistincomeResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprEditDescriptionByPaymentId(&self, request: BkpreditdescriptionbypaymentidRequest) -> BkpreditdescriptionbypaymentidResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BkprEditDescriptionByOutpoint(&self, request: BkpreditdescriptionbyoutpointRequest) -> BkpreditdescriptionbyoutpointResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn BlacklistRune(&self, request: BlacklistruneRequest) -> BlacklistruneResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn CheckRune(&self, request: CheckruneRequest) -> CheckruneResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn CreateRune(&self, request: CreateruneRequest) -> CreateruneResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn ShowRunes(&self, request: ShowrunesRequest) -> ShowrunesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneUnreserve(&self, request: AskreneunreserveRequest) -> AskreneunreserveResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneListLayers(&self, request: AskrenelistlayersRequest) -> AskrenelistlayersResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneCreateLayer(&self, request: AskrenecreatelayerRequest) -> AskrenecreatelayerResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneRemoveLayer(&self, request: AskreneremovelayerRequest) -> AskreneremovelayerResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneReserve(&self, request: AskrenereserveRequest) -> AskrenereserveResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneAge(&self, request: AskreneageRequest) -> AskreneageResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn GetRoutes(&self, request: GetroutesRequest) -> GetroutesResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneDisableNode(&self, request: AskrenedisablenodeRequest) -> AskrenedisablenodeResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneInformChannel(&self, request: AskreneinformchannelRequest) -> AskreneinformchannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneCreateChannel(&self, request: AskrenecreatechannelRequest) -> AskrenecreatechannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneUpdateChannel(&self, request: AskreneupdatechannelRequest) -> AskreneupdatechannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneBiasChannel(&self, request: AskrenebiaschannelRequest) -> AskrenebiaschannelResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn AskReneListReservations(&self, request: AskrenelistreservationsRequest) -> AskrenelistreservationsResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn InjectPaymentOnion(&self, request: InjectpaymentonionRequest) -> InjectpaymentonionResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn InjectOnionMessage(&self, request: InjectonionmessageRequest) -> InjectonionmessageResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn Xpay(&self, request: XpayRequest) -> XpayResponse {
dbg!(request);
unimplemented!();
}

#[allow(non_snake_case)]
pub fn SignMessageWithKey(&self, request: SignmessagewithkeyRequest) -> SignmessagewithkeyResponse {
dbg!(request);
unimplemented!();
}

} // End of struct Node