[project]
name = "gl-testing"
version = "0.3.1"
description = ""
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flaky>=3.8.1",
    "gl-client",
    "grpcio-tools>=1.81.1",
    "grpcio>=1.81.1",
    "httpx[http2]==0.27.2",
    "purerpc>=0.8.0",
    "pyln-client>=26.6.6",
    "pyln-testing>=26.6.6",
    "pytest-timeout>=2.3.1",
    "pytest-xdist>=3.6.1",
    "rich>=13.9.3",
    "sh>=1.14.3",
    "sonora>=0.2.3",
    "cln-version-manager",
    "bip39>=0.0.2",
]


[tool.uv]
package = true

[tool.uv.sources]
gl-client = { workspace = true }
cln-version-manager = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "gltesting",
    "plugins",
]
exclude = [
    "**/.#*",
    "**/*~",
    "**/*.swp",
]
