name: Check Formatting

on:
  pull_request:
    types:
      - synchronize
      - opened
  workflow_dispatch:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.73
        components: rustfmt
    
    - name: Check Rust Formatting
      continue-on-error: true
      run: |
        make check-rustfmt
