name: Rust Unit Test

on:
  pull_request:
    types:
      - synchronize
      - opened
  workflow_dispatch:
  merge_group:

jobs:
  unit_test:
    name: Rust unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: arduino/setup-protoc@v2
        with:
            version: "23.2"  # Fixed since we mount the path below
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: (cd libs; cargo test)